name: Docker Image Build

on:
  push:
    branches:
      - main # main 브랜치에 push 될 때 실행
  pull_request:
    branches:
      - main # main 브랜치에 pull request가 생성될 때 실행

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: bootJar

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ github.sha }}